In [ ]:
import pandas as pd

In [ ]:
indicators = pd.read_csv('indicators_2020.csv', sep=';')
indicators

,Wijken en buurten,Regioaanduiding/Soort regio (omschrijving),Regioaanduiding/Codering (code),Bevolking/Aantal inwoners (aantal),Bevolking/Leeftijdsgroepen/15 tot 25 jaar (aantal),Bevolking/Leeftijdsgroepen/25 tot 45 jaar (aantal),Bevolking/Leeftijdsgroepen/45 tot 65 jaar (aantal),Bevolking/Leeftijdsgroepen/65 jaar of ouder (aantal),Bevolking/Personen met een migratieachtergrond/Westers totaal (aantal),Bevolking/Personen met een migratieachtergrond/Niet-westers/Niet-westers totaal (aantal),Wonen/Gemiddelde WOZ-waarde van woningen (x 1 000 euro),Opleidingsniveau/Opleidingsniveau laag (aantal),Opleidingsniveau/Opleidingsniveau middelbaar (aantal),Opleidingsniveau/Opleidingsniveau hoog (aantal),Inkomen/Inkomen van personen/Gemiddeld inkomen per inwoner (x 1 000 euro),Inkomen/Inkomen van personen/40% personen met laagste inkomen (%),Inkomen/Inkomen van personen/20% personen met hoogste inkomen (%)
0,Amsterdam,Gemeente,GM0363,872757,108636,317667,210376,110959,170164,314818,415,160230,206500,338970,32.4,39.7,24.6
1,Burgwallen-Oude Zijde,Wijk,WK036300,4465,695,2190,940,425,1510,775,469,450,1160,2540,32.8,40.5,22.5
2,Kop Zeedijk,Buurt,BU03630000,1100,125,575,275,75,395,200,423,40,350,670,37.0,33.0,27.7
3,Oude Kerk e.o.,Buurt,BU03630001,730,130,370,130,70,250,125,431,200,150,290,31.5,43.3,19.2
4,Burgwallen Oost,Buurt,BU03630002,1615,255,780,310,175,540,320,462,160,440,890,29.2,43.7,18.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,Gein Noordoost,Buurt,BU03639702,3265,400,700,1120,600,480,1105,318,540,1220,920,29.5,31.1,22.4
575,Gein Zuidoost,Buurt,BU03639703,3375,340,915,1025,605,370,1730,258,780,1060,860,24.4,41.8,13.8
576,Driemond,Wijk,WK036398,1625,190,350,495,285,160,185,357,270,600,350,28.5,36.8,22.6
577,Dorp Driemond,Buurt,BU03639800,1490,175,320,455,280,150,175,333,250,560,310,28.4,37.0,21.5
578,Landelijk gebied Driemond,Buurt,BU03639801,135,20,30,40,10,10,5,758,20,30,50,29.6,.,.

In [ ]:
indicators.columns = ['neighborhood','type of region','code','population (count)',
                      'age 15-25 (count)','age 25-45 (count)','age 45-65 (count)','age >65 (count)',
                      'Western migrants (count)','non-Western migrants (count)','property value (x1000 euro)',
                      'education low (count)','education secondary (count)','education high (count)',
                      'income per inhabitant (x1000 euro)','40% with lowest income (%)','20% with highest income (%)']
indicators

,neighborhood,type of region,code,population (count),age 15-25 (count),age 25-45 (count),age 45-65 (count),age >65 (count),Western migrants (count),non-Western migrants (count),property value (x1000 euro),education low (count),education secondary (count),education high (count),income per inhabitant (x1000 euro),40% with lowest income (%),20% with highest income (%)
0,Amsterdam,Gemeente,GM0363,872757,108636,317667,210376,110959,170164,314818,415,160230,206500,338970,32.4,39.7,24.6
1,Burgwallen-Oude Zijde,Wijk,WK036300,4465,695,2190,940,425,1510,775,469,450,1160,2540,32.8,40.5,22.5
2,Kop Zeedijk,Buurt,BU03630000,1100,125,575,275,75,395,200,423,40,350,670,37.0,33.0,27.7
3,Oude Kerk e.o.,Buurt,BU03630001,730,130,370,130,70,250,125,431,200,150,290,31.5,43.3,19.2
4,Burgwallen Oost,Buurt,BU03630002,1615,255,780,310,175,540,320,462,160,440,890,29.2,43.7,18.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,Gein Noordoost,Buurt,BU03639702,3265,400,700,1120,600,480,1105,318,540,1220,920,29.5,31.1,22.4
575,Gein Zuidoost,Buurt,BU03639703,3375,340,915,1025,605,370,1730,258,780,1060,860,24.4,41.8,13.8
576,Driemond,Wijk,WK036398,1625,190,350,495,285,160,185,357,270,600,350,28.5,36.8,22.6
577,Dorp Driemond,Buurt,BU03639800,1490,175,320,455,280,150,175,333,250,560,310,28.4,37.0,21.5
578,Landelijk gebied Driemond,Buurt,BU03639801,135,20,30,40,10,10,5,758,20,30,50,29.6,.,.

In [ ]:
indicators['age 15-25 (%)'] = round(100 * indicators['age 15-25 (count)'] / indicators['population (count)'], 2)
indicators['age 25-45 (%)'] = round(100 * indicators['age 25-45 (count)'] / indicators['population (count)'], 2)
indicators['age 45-65 (%)'] = round(100 * indicators['age 45-65 (count)'] / indicators['population (count)'], 2)
indicators['age >65 (%)'] = round(100 * indicators['age >65 (count)'] / indicators['population (count)'], 2)

,neighborhood,type of region,code,population (count),age 15-25 (count),age 25-45 (count),age 45-65 (count),age >65 (count),Western migrants (count),non-Western migrants (count),...,education low (count),education secondary (count),education high (count),income per inhabitant (x1000 euro),40% with lowest income (%),20% with highest income (%),age 15-25 (%),age 25-45 (%),age 45-65 (%),age >65 (%)
0,Amsterdam,Gemeente,GM0363,872757,108636,317667,210376,110959,170164,314818,...,160230,206500,338970,32.4,39.7,24.6,12.45,36.40,24.10,12.71
1,Burgwallen-Oude Zijde,Wijk,WK036300,4465,695,2190,940,425,1510,775,...,450,1160,2540,32.8,40.5,22.5,15.57,49.05,21.05,9.52
2,Kop Zeedijk,Buurt,BU03630000,1100,125,575,275,75,395,200,...,40,350,670,37.0,33.0,27.7,11.36,52.27,25.00,6.82
3,Oude Kerk e.o.,Buurt,BU03630001,730,130,370,130,70,250,125,...,200,150,290,31.5,43.3,19.2,17.81,50.68,17.81,9.59
4,Burgwallen Oost,Buurt,BU03630002,1615,255,780,310,175,540,320,...,160,440,890,29.2,43.7,18.3,15.79,48.30,19.20,10.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,Gein Noordoost,Buurt,BU03639702,3265,400,700,1120,600,480,1105,...,540,1220,920,29.5,31.1,22.4,12.25,21.44,34.30,18.38
575,Gein Zuidoost,Buurt,BU03639703,3375,340,915,1025,605,370,1730,...,780,1060,860,24.4,41.8,13.8,10.07,27.11,30.37,17.93
576,Driemond,Wijk,WK036398,1625,190,350,495,285,160,185,...,270,600,350,28.5,36.8,22.6,11.69,21.54,30.46,17.54
577,Dorp Driemond,Buurt,BU03639800,1490,175,320,455,280,150,175,...,250,560,310,28.4,37.0,21.5,11.74,21.48,30.54,18.79
578,Landelijk gebied Driemond,Buurt,BU03639801,135,20,30,40,10,10,5,...,20,30,50,29.6,.,.,14.81,22.22,29.63,7.41

In [ ]:
indicators['migrants (%)'] = round(100 * (indicators['Western migrants (count)'] + indicators['non-Western migrants (count)']) / indicators['population (count)'], 2)
indicators['Western migrants (%)'] = round(100 * indicators['Western migrants (count)'] / indicators['population (count)'], 2)
indicators['non-Western migrants (%)'] = round(100 * indicators['non-Western migrants (count)'] / indicators['population (count)'], 2)

In [ ]:
indicators['education low (count)'] = indicators['education low (count)'].str.extract(pat='(\d+)', expand=False).astype('Int64')
indicators['education secondary (count)'] = indicators['education secondary (count)'].str.extract(pat='(\d+)', expand=False).astype('Int64')
indicators['education high (count)'] = indicators['education high (count)'].str.extract(pat='(\d+)', expand=False).astype('Int64')

indicators['education low (%)'] = round(100 * indicators['education low (count)'] / indicators['population (count)'], 2)
indicators['education secondary (%)'] = round(100 * indicators['education secondary (count)'] / indicators['population (count)'], 2)
indicators['education high (%)'] = round(100 * indicators['education high (count)'] / indicators['population (count)'], 2)

In [ ]:
indicators

,neighborhood,type of region,code,population (count),age 15-25 (count),age 25-45 (count),age 45-65 (count),age >65 (count),Western migrants (count),non-Western migrants (count),...,age 15-25 (%),age 25-45 (%),age 45-65 (%),age >65 (%),migrants (%),Western migrants (%),non-Western migrants (%),education low (%),education secondary (%),education high (%)
0,Amsterdam,Gemeente,GM0363,872757,108636,317667,210376,110959,170164,314818,...,12.45,36.40,24.10,12.71,55.57,19.50,36.07,<NA>,23.66,38.84
1,Burgwallen-Oude Zijde,Wijk,WK036300,4465,695,2190,940,425,1510,775,...,15.57,49.05,21.05,9.52,51.18,33.82,17.36,10.08,25.98,56.89
2,Kop Zeedijk,Buurt,BU03630000,1100,125,575,275,75,395,200,...,11.36,52.27,25.00,6.82,54.09,35.91,18.18,3.64,31.82,60.91
3,Oude Kerk e.o.,Buurt,BU03630001,730,130,370,130,70,250,125,...,17.81,50.68,17.81,9.59,51.37,34.25,17.12,27.4,20.55,39.73
4,Burgwallen Oost,Buurt,BU03630002,1615,255,780,310,175,540,320,...,15.79,48.30,19.20,10.84,53.25,33.44,19.81,9.91,27.24,55.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,Gein Noordoost,Buurt,BU03639702,3265,400,700,1120,600,480,1105,...,12.25,21.44,34.30,18.38,48.55,14.70,33.84,16.54,37.37,28.18
575,Gein Zuidoost,Buurt,BU03639703,3375,340,915,1025,605,370,1730,...,10.07,27.11,30.37,17.93,62.22,10.96,51.26,23.11,31.41,25.48
576,Driemond,Wijk,WK036398,1625,190,350,495,285,160,185,...,11.69,21.54,30.46,17.54,21.23,9.85,11.38,16.62,36.92,21.54
577,Dorp Driemond,Buurt,BU03639800,1490,175,320,455,280,150,175,...,11.74,21.48,30.54,18.79,21.81,10.07,11.74,16.78,37.58,20.81
578,Landelijk gebied Driemond,Buurt,BU03639801,135,20,30,40,10,10,5,...,14.81,22.22,29.63,7.41,11.11,7.41,3.70,14.81,22.22,37.04

In [ ]:
indicators.columns

Index(['neighborhood', 'type of region', 'code', 'population (count)',
       'age 15-25 (count)', 'age 25-45 (count)', 'age 45-65 (count)',
       'age >65 (count)', 'Western migrants (count)',
       'non-Western migrants (count)', 'property value (x1000 euro)',
       'education low (count)', 'education secondary (count)',
       'education high (count)', 'income per inhabitant (x1000 euro)',
       '40% with lowest income (%)', '20% with highest income (%)',
       'age 15-25 (%)', 'age 25-45 (%)', 'age 45-65 (%)', 'age >65 (%)',
       'migrants (%)', 'Western migrants (%)', 'non-Western migrants (%)',
       'education low (%)', 'education secondary (%)', 'education high (%)'],
      dtype='object')

In [ ]:
mod_indicators_2020 = indicators[['neighborhood', 'type of region', 'code', 'population (count)',
                                  'age 15-25 (%)', 'age 25-45 (%)', 'age 45-65 (%)', 'age >65 (%)',
                                  'migrants (%)', 'Western migrants (%)', 'non-Western migrants (%)',
                                  'education low (%)', 'education secondary (%)', 'education high (%)',
                                  'property value (x1000 euro)', 'income per inhabitant (x1000 euro)',
                                  '40% with lowest income (%)', '20% with highest income (%)']]
mod_indicators_2020

,neighborhood,type of region,code,population (count),age 15-25 (%),age 25-45 (%),age 45-65 (%),age >65 (%),migrants (%),Western migrants (%),non-Western migrants (%),education low (%),education secondary (%),education high (%),property value (x1000 euro),income per inhabitant (x1000 euro),40% with lowest income (%),20% with highest income (%)
0,Amsterdam,Gemeente,GM0363,872757,12.45,36.40,24.10,12.71,55.57,19.50,36.07,<NA>,23.66,38.84,415,32.4,39.7,24.6
1,Burgwallen-Oude Zijde,Wijk,WK036300,4465,15.57,49.05,21.05,9.52,51.18,33.82,17.36,10.08,25.98,56.89,469,32.8,40.5,22.5
2,Kop Zeedijk,Buurt,BU03630000,1100,11.36,52.27,25.00,6.82,54.09,35.91,18.18,3.64,31.82,60.91,423,37.0,33.0,27.7
3,Oude Kerk e.o.,Buurt,BU03630001,730,17.81,50.68,17.81,9.59,51.37,34.25,17.12,27.4,20.55,39.73,431,31.5,43.3,19.2
4,Burgwallen Oost,Buurt,BU03630002,1615,15.79,48.30,19.20,10.84,53.25,33.44,19.81,9.91,27.24,55.11,462,29.2,43.7,18.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,Gein Noordoost,Buurt,BU03639702,3265,12.25,21.44,34.30,18.38,48.55,14.70,33.84,16.54,37.37,28.18,318,29.5,31.1,22.4
575,Gein Zuidoost,Buurt,BU03639703,3375,10.07,27.11,30.37,17.93,62.22,10.96,51.26,23.11,31.41,25.48,258,24.4,41.8,13.8
576,Driemond,Wijk,WK036398,1625,11.69,21.54,30.46,17.54,21.23,9.85,11.38,16.62,36.92,21.54,357,28.5,36.8,22.6
577,Dorp Driemond,Buurt,BU03639800,1490,11.74,21.48,30.54,18.79,21.81,10.07,11.74,16.78,37.58,20.81,333,28.4,37.0,21.5
578,Landelijk gebied Driemond,Buurt,BU03639801,135,14.81,22.22,29.63,7.41,11.11,7.41,3.70,14.81,22.22,37.04,758,29.6,.,.

In [ ]:
mod_indicators_2020['property value (x1000 euro)'] = mod_indicators_2020['property value (x1000 euro)'].str.extract(pat='([0-9]+[,./]*[0-9]*)', expand=False).astype('float')
mod_indicators_2020['income per inhabitant (x1000 euro)'] = mod_indicators_2020['income per inhabitant (x1000 euro)'].str.extract(pat='([0-9]+[,./]*[0-9]*)', expand=False).astype('float')
mod_indicators_2020['40% with lowest income (%)'] = mod_indicators_2020['40% with lowest income (%)'].str.extract(pat='([0-9]+[,./]*[0-9]*)', expand=False).astype('float')
mod_indicators_2020['20% with highest income (%)'] = mod_indicators_2020['20% with highest income (%)'].str.extract(pat='([0-9]+[,./]*[0-9]*)', expand=False).astype('float')

/var/folders/nj/wvtqcb0d2hvghdd39j0m5xt40000gn/T/ipykernel_26161/2107081235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mod_indicators_2020['property value (x1000 euro)'] = mod_indicators_2020['property value (x1000 euro)'].str.extract(pat='([0-9]+[,./]*[0-9]*)', expand=False).astype('float')
/var/folders/nj/wvtqcb0d2hvghdd39j0m5xt40000gn/T/ipykernel_26161/2107081235.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mod_indicators_2020['income per inhabitant (x1000 euro)'] = mod_indicators_2020['income per inhabitant (x1000 euro)'].str.extract(pat='([0-9]+[,./]*[0-9]*)', expand=False).astype('float')
/var/folders/nj/wvtqcb0d2hvghdd39j0m5xt40000gn/T/ipykernel_26161/2107081235.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mod_indicators_2020['40% with lowest income (%)'] = mod_indicators_2020['40% with lowest income (%)'].str.extract(pat='([0-9]+[,./]*[0-9]*)', expand=False).astype('float')
/var/folders/nj/wvtqcb0d2hvghdd39j0m5xt40000gn/T/ipykernel_26161/2107081235.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mod_indicators_2020['20% with highest income (%)'] = mod_indicators_2020['20% with highest income (%)'].str.extract(pat='([0-9]+[,./]*[0-9]*)', expand=False).astype('float')

In [ ]:
mod_indicators_2020

,neighborhood,type of region,code,population (count),age 15-25 (%),age 25-45 (%),age 45-65 (%),age >65 (%),migrants (%),Western migrants (%),non-Western migrants (%),education low (%),education secondary (%),education high (%),property value (x1000 euro),income per inhabitant (x1000 euro),40% with lowest income (%),20% with highest income (%)
0,Amsterdam,Gemeente,GM0363,872757,12.45,36.40,24.10,12.71,55.57,19.50,36.07,<NA>,23.66,38.84,415.0,32.4,39.7,24.6
1,Burgwallen-Oude Zijde,Wijk,WK036300,4465,15.57,49.05,21.05,9.52,51.18,33.82,17.36,10.08,25.98,56.89,469.0,32.8,40.5,22.5
2,Kop Zeedijk,Buurt,BU03630000,1100,11.36,52.27,25.00,6.82,54.09,35.91,18.18,3.64,31.82,60.91,423.0,37.0,33.0,27.7
3,Oude Kerk e.o.,Buurt,BU03630001,730,17.81,50.68,17.81,9.59,51.37,34.25,17.12,27.4,20.55,39.73,431.0,31.5,43.3,19.2
4,Burgwallen Oost,Buurt,BU03630002,1615,15.79,48.30,19.20,10.84,53.25,33.44,19.81,9.91,27.24,55.11,462.0,29.2,43.7,18.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,Gein Noordoost,Buurt,BU03639702,3265,12.25,21.44,34.30,18.38,48.55,14.70,33.84,16.54,37.37,28.18,318.0,29.5,31.1,22.4
575,Gein Zuidoost,Buurt,BU03639703,3375,10.07,27.11,30.37,17.93,62.22,10.96,51.26,23.11,31.41,25.48,258.0,24.4,41.8,13.8
576,Driemond,Wijk,WK036398,1625,11.69,21.54,30.46,17.54,21.23,9.85,11.38,16.62,36.92,21.54,357.0,28.5,36.8,22.6
577,Dorp Driemond,Buurt,BU03639800,1490,11.74,21.48,30.54,18.79,21.81,10.07,11.74,16.78,37.58,20.81,333.0,28.4,37.0,21.5
578,Landelijk gebied Driemond,Buurt,BU03639801,135,14.81,22.22,29.63,7.41,11.11,7.41,3.70,14.81,22.22,37.04,758.0,29.6,NaN,NaN

In [ ]:
mod_indicators_2020.to_csv('/Users/vanh/Documents/Master/Thesis/w.nosync/MSc-Thesis-Gentrification-and-storefront-signage/Data/mod_indicators_2020.csv')